language: python
python:
  - "3.6"
sudo: false
cache:
  pip: true
before_install:
  - pip3 install -U pip
install:
  - pip3 install -r requirements.txt
  - pip3 install -r requirements-dev.txt
  - python3 setup.py install
script: py.test reskit/tests/
